### ISSUE TITLE
Add license to the website

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#11]
Add license to the website. @tillkamppeter please suggest what license should be used for the website.

**Comment by iramcdonald** [comment]
Hi,

I respectfully suggest Apache 2.0 license:

https://www.apache.org/licenses/LICENSE-2.0

The IEEE-ISTO PWG decided to move everything to Apache 2.0 after
thorough research and discussion within PWG Steering Committee.

Also, Apache 2.0 is the license chosen by Apple for all of their open
source projects (including CUPS).  Any form of GPL is poisonous
to takeup by corporations.  Some of the other popular licenses, like
BSD and MIT are fine in principal, but have ambiguities or omissions
that were explictly fixed in Apache 2.0.

Cheers,
- Ira



Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by tillkamppeter** [comment]
Ira, thank you very much. This sounds reasonable. Let us take Apache 2.0 then.
