### ISSUE TITLE
CUPS project page - CSS issues

### ISSUE THREAD

**Issue by dheeraj135** [OpenPrinting/openprinting.github.io#124]
CUPS logo dimensions on this page need to be corrected. The current size is too large.

![Screenshot from 2021-02-21 22-42-43](https://user-images.githubusercontent.com/28601604/108624001-11dc4080-7468-11eb-9c21-4fab34faef1e.png)

**Comment by tillkamppeter** [comment]
For me the logo is still huge in Chromium (of Ubuntu Hirsute) and correct in Firefox.

But should this issue not get removed to the CUPS repository as the CUPS site is coming from there.

**Comment by tillkamppeter** [comment]
@michaelrsweet ?

**Comment by michaelrsweet** [comment]
@tillkamppeter @dheeraj135 Weird, I didn't see this when I tested against Chrome, but I'll add explicit dimensions to the HTML template since it obviously isn't picking up the dimensions from the CSS...

**Comment by michaelrsweet** [comment]
[gh-pages ada14b693] Add HTML image dimensions to fix Chrome rendering bug.

May take a few minutes to sync up on github.io...

**Comment by michaelrsweet** [comment]
I updated chrome and am getting the same issue, even with the dimensions being specified in the HTML!

Definitely a Chrome bug, and after much experimentation it only happens when you specify the source in CSS, so I've pushed a change that moves that to the HTML...

[gh-pages 59641bc86] Don't use CSS for the navbar icon, as Chrome has a major rendering bug. Just use plain HTML.

**Comment by michaelrsweet** [comment]
[gh-pages b86979729] Fix search controls for Chrome...

**Comment by michaelrsweet** [comment]
OK, seems to be rendering consistently between Chrome, Firefox, and Safari for me...

**Comment by tillkamppeter** [comment]
OK, now it works for me.

**Comment by dheeraj135** [comment]
It's now working for me. Thanks @michaelrsweet .
