### ISSUE TITLE
Add content to the 'Donations' page

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#35]
Add content to the `Donations` page.
Depends on: #34

**Comment by dheeraj135** [comment]
@tillkamppeter As it was discussed on Issue #34 , we cannot donate directly to OP. So, what is the exact way to donate money to OP? No, such way was mentioned on the [previous page](https://wiki.linuxfoundation.org/openprinting/database/howtocontribute#money_hardware_events).

**Comment by iramcdonald** [comment]
Hi,

As Till and I pointed out on issue#34, since OP is not a legally
incorporated entity
in its own right (i.e., separate from Linux Foundation), no one can donate
directly
to OP.  Donations to Linux Foundation that are earmarked (by donor comments)
for OP are inherently fragile and are not legally binding on Linux
Foundation.

People *can* donate their time (as designers, coders, etc.).  Also, as Till
said, we
should say that we are accepting hardware samples for testing and
development.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by tillkamppeter** [comment]
We could also accept donations for travel of developers to conferences. In this case the developer needs to get reimbursed directly by the donator.

**Comment by iramcdonald** [comment]
Hi Till,

For direct reimbursement of developers for travel by donors, we should bear
in mind that in some countries, (e.g., USA), the donor and developer both
have
to report the donation to the federal tax authorities (e.g., IRS in USA) by
law.

That's why I would prefer not to mention this procedure on our web pages.

Cheers,
- Ira

PS - Speaking here as the owner of a US corporation who spends a lot of
time on US tax law every year, but NOT a lawyer.

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434
