### ISSUE TITLE
Add a collection for 'Driverless Printing'

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#38]
`Driverless Printing` should be made as a collection and a page should be made with the link embedded in the title bar as there is now: 
![image](https://user-images.githubusercontent.com/12633577/52178696-a8912280-27f7-11e9-9529-a2391d7ed54d.png)

**Comment by dheeraj135** [comment]
@sahilarora535 What will this collection contain?

**Comment by Sharadd15** [comment]
@dheeraj135  are you working on this?

**Comment by dheeraj135** [comment]
@Sharadd15 If you want to work on this, Please go ahead.

**Comment by Sharadd15** [comment]
Okay i am working on this issue. @sahilarora535 please can you elaborate a bit about what we want the page should contain ?

**Comment by iramcdonald** [comment]
Hi,

I suggest that Till could provide appropriate Driverless Printing overview.

OpenPrinting committed to IEEE-ISTO Printer Working Group last May
to include brief notes about the IPP Everywhere standard and PWG
manufacturer self-certification tools and process and put the IPP
Everywhere logo on the OP Driverless Printing new webpage.

Here are the links:

http://www.pwg.org/ipp/everywhere.html

https://ftp.pwg.org/pub/pwg/candidates/cs-ippeve10-20130128-5100.14.pdf

https://ftp.pwg.org/pub/pwg/candidates/cs-ippeveselfcert10-20160219-5100.20.pdf

Please note that both spec and self-cert manual are being updated to v1.1
right
now, so these links will need to be updated w/in a couple of months.

Also, attached is the IPP Everywhere logo (which has an international
trademark).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by dheeraj135** [comment]
Hi @iramcdonald ,
The attachment was not received. Can you please share link to the logo?

**Comment by iramcdonald** [comment]
Hi,

Logo is a PNG image on the top left of the main IPP Everywhere page.
There is *intentionally* no public direct link to the logo, because only
vendors w/ certified printers or collaborating standards bodies (e.g.,
OP) can legally show the logo - cut-and-paste worked fine for me.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by Sharadd15** [comment]
hi @iramcdonald ,
We have to put the logo and the brief notes(read the document shared by you and write briefly about it) from the links you have shared and the links as well?
anything else ?

**Comment by iramcdonald** [comment]
Hi,

Yes, this is why Till needs to provide input here.  We should briefly
talk about the Apple AirPrint driverless printing infrastructure (which
is also based on IPP/1.1 and differs by only a few attributes from
IPP Everywhere).  But AirPrint *also* includes the Apple proprietary
URF raster format (which like PWG Raster is a subset of CUPS
Raster).  Likewise, Wi-Fi Direct Printing (I forgot the exact name)
includes yet another HP proprietary raster format called PCLm
(no relationship to HP PCL at all - it's a PDF wrapper around
raster data).

Till has done slides in recent Joint PWG/OP Summit meetings
about Driverless Printing that would be good source material.

OP and CUPS Filters take a neutral position on these three
flavors of Driverless Printing (and in fact normalizes them to
all look like the standard IPP Everywhere to IPP clients).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by dheeraj135** [comment]
@tillkamppeter Can you please provide us some more input on Driverless printing?

**Comment by tillkamppeter** [comment]
Here are my most recent [slides of cups-filters/ippusbxd](https://ftp.pwg.org/pub/pwg/liaison/openprinting/presentations/cups-filters-ippusbxd-2018.pdf) containing a lot of info about driverless printing.
These are [Mike Sweet's slides about CUPS](https://ftp.pwg.org/pub/pwg/liaison/openprinting/presentations/cups-plenary-may-18.pdf) also containing info about driverless printing.
Both are from the [May 2018 Joint OpenPrinting Summit/PWG Meeting](http://pwg.org/chair/meeting-info/may-2018-sunnyvale.html).
Driverless Printing means that to be able to print on a given printer no software or data specific to that printer model needs to be installed on the client. The client should even be able to print on printers which did not exist yet when the client's software was released. The printer must use known page description languages and must inform the client about its capabilities on request.
Driverless printing is especially important for Linux and similar operating systems as they are often not explicitly supported by the manufacturers supplying drivers for them. Originally the driverless printing standards were created to allow smartphones, tablets, and similar mobile devices to print, as these come with several different and new operating systems. Even very cheap printers do driverless printing (people want to print from phones), so it is easy to get a printer for Linux nowadays. 
There got four driverless printing standards established, but they all are based on the printer advertising itself via DNS-SD in the network, communicating with clients via IPP, and supporting a selection out of four known Page Description Languages (PDLs). The difference is merely only which selection of PDLs is supported.
Due to this we actually do not distinguish between the standards any more ans simply call it "driverless IPP printing", or simply "driverless printing".
Here are the 4 standards and their PDLs:
- Apple AirPrint: Apple Raster/URF, PDF (Apple's standard to print from iOS, most common and the oldest driverless printing standard)
- PWG's IPP Everywhere: PWG Raster, PDF (from the [Printer Working Group (PWG)](http://www.pwg.org/), completely open PWG Raster format)
- Mopria: PCLm, PWG Raster, PDF
- Wi-Fi Direct: PCLm, PWG Raster, PDF (printers must also work as a Wi-Fi server so that phones can print without an existing Wi-Fi infrastructure)

Apple Raster (aka URF) is Apple's own raster format for printing from iOS. Specs got only known when support for it got added to CUPS (version 2.2.2). It is similar to CUPS and PWG Raster but with much simpler page headers.
PWG Raster is, as all the PWG's standards work, completely free and fully documented, as well as the PWG's IPP Everywhere standard.
PCLm has nothing to do with PCL, it is a raster-only subset of the PDF format. So you can display every PCLm file with a PDF viewer, or print it on a PDF-only printer, but you cannot print arbitrary PDF files on a PCLm-only printer.
The workflow of driverless printing is always the same:

1. The printer advertises itself by DNS-SD, with a summary of its most important capability information (especially also its PDLs and a one-line-string super summary in case of AirPrint printers) in its DNS-SD record.
2. Clients find these printers via DNS-SD.
3. The client polls the full capabilities info from the printer sending a get-printer-attributes IPP request. The printer returns a long list of info, especially paper sizes and types, unprintable margins, resolutions, input trays, finishers, quality settings, all user-settable options, ...
4. CUPS or cups-browsed on the client generate PPD files from this info and create print queues for each printer.
5. The print dialogs of the applications show the printers and allow access to all the user-settable options.
6. The user prints a job. The PDF from the application is turned into one of the PDLs which the printer supports by cups-filters. The settings selected by the user are passed along with the job as IPP attributes.
7. The printer prints the job and thanks to IPP the status can be observed, toner levels and any errors can get reported to the client.
8. If the printer is shut down, its queue will get automatically removed. So no clutter of print queues as souvenir of all the networks you have visited.

I hope this info is helpful.

**Comment by dheeraj135** [comment]
@Sharadd15 Are you working on this issue?

**Comment by Sharadd15** [comment]
@dheeraj135 yes I am working on this

**Comment by Sharadd15** [comment]
@tillkamppeter do we have add all the content on one page ?
or do we have to create a collection of pages ?
If we are creating collection of pages then in which way do we have to sort the content?

**Comment by dheeraj135** [comment]
@Sharadd15 I suggest, create pages like "What is driverless printing?", "How driverless printing works?" and "Common Standards.". We will need a page for driverless printing(in the _pages directory).

**Comment by tillkamppeter** [comment]
I think the text that I have written in my comment is not too long for a single page. Splitting it up on several pages could even make each page very small. Only if you add a lot of additional text one could consider a splitting (or at least add section titles and make them accessible by a table of contents/navigation sidebar.
